services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_USER=springer'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'



    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
